// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lavphfdwptcywfldfwvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhdnBoZmR3cHRjeXdmbGRmd3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjMxNTksImV4cCI6MjA3MDAzOTE1OX0.8cX0JE20Ko6QiNLXDuL_N9dE_aiovgQ2b4teqZLLJWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});